### ISSUE TITLE
1.1.1 doesn't create CSS file with -s

### ISSUE THREAD

**Issue by zoeyronain** [AdventureBear/trot#3]
just installed with latest version on NPM, and it's not creating the CSS file when generating a component.

schatzgraber ॐ  /Volumes/2TB Green/Code/test:(~|git@master!)
1205 ± trot -c test -s                                                                                                                                             
Creating React component:
  - Component Name: test
  - EMCAScript Version: 6
  - Folder: ./
  - CSS file created: No
New file created:  ././/test.js
schatzgraber ॐ  /Volumes/2TB Green/Code/test:(~|git@master!)
1206 ± ls                                                                                                                                                            
package.json test.js

**Comment by AdventureBear** [comment]
Zoey thanks for this comment, i'll test this out, I may need to push or publish my latest release. Thanks.

**Comment by AdventureBear** [comment]
Zoey, this issue has been updated with the latest release which is version 1.x.x and therefore causes breaking changes.  to correct the CSS issue, please doe the following: 

    npm uninstall trot -g  //uninstalls current version of trot
    npm install trot -g //installs current version

Please review the readme file. Breaking changes/new additions include 'comp' and 'nest' commands. 

Old version: 
    trot -c Test -f src -s   

New version:
    trot comp -c Test -f src -s Y

Note that in version 1.1.x and up there is a new command called 'nest' that allows you to nest your newly created components in a parent component.   (See README). 

Please let me know if this doesn't fix the issue you were having.
