### ISSUE TITLE
Add templates based on component type

### ISSUE THREAD

**Issue by jluo9612** [AdventureBear/trot#8]
This is just a suggestion for a potential feature. Is it possible to generate component boilerplate based on their type? A starting point could be Stateless Components, Class Components, etc.

**Comment by AdventureBear** [comment]
yes that's a good idea.  What would the command like look like for that?

**Comment by jluo9612** [comment]
Adding a flag to the create component command. Something like: `trot comp -c ComponentName --stateless` or `trot comp -c ComponentName --class`

**Comment by AdventureBear** [comment]
got it, this is a good idea.  I'll work on it.
